// ============================================================
// TYPING LEVELS — 20 levels across 4 groups (ages 7-18)
// ============================================================

const TYPING_SHEETS_TO_COMPLETE = 20;
const TYPING_PASS_ACCURACY      = 80;  // % accuracy required
const TYPING_PROMPTS_PER_SHEET  = 10;
const TYPING_PTS_PER_SHEET      = 10;

const TYPING_LEVELS = [
  // ── Beginner (ages 7-9) ──────────────────────────────────
  { id: 0, name: 'Home Row Left',       emoji: '🤚', color: '#fd9644', group: 'Beginner',
    prompts: ['fff', 'ddd', 'sss', 'aaa', 'fds', 'sdf', 'asdf', 'fdsa',
              'add', 'sad', 'fad', 'dad', 'ads', 'dads', 'fads', 'adds',
              'a s d f', 'f d s a', 'asdf fdsa', 'fads dads'] },

  { id: 1, name: 'Home Row Right',      emoji: '🤙', color: '#fd9644', group: 'Beginner',
    prompts: ['jjj', 'kkk', 'lll', 'jkl', 'lkj', 'jkl;', ';lkj',
              'jjkk', 'llkk', 'jklj', 'lkjl', 'j k l', 'l k j',
              'jkl jkl', ';lkj jkl;', 'jjjkkklll', 'lllkkkjjj',
              'jkl; ;lkj', 'jjll kkjj', 'klj jlk'] },

  { id: 2, name: 'Home Row All',        emoji: '⌨️', color: '#fd9644', group: 'Beginner',
    prompts: ['asdf jkl', 'jkl; asdf', 'asdfjkl',
              'fall', 'half', 'hall', 'flask', 'flag', 'glad', 'lad',
              'disk', 'dusk', 'ask', 'all', 'shall', 'skill', 'fill',
              'alas', 'flash', 'slash', 'glass', 'class'] },

  { id: 3, name: 'Three-Letter Words',  emoji: '📝', color: '#fd9644', group: 'Beginner',
    prompts: ['the', 'cat', 'dog', 'run', 'big', 'hat', 'sit',
              'fit', 'hop', 'top', 'map', 'nap', 'lap', 'tip',
              'dip', 'fog', 'log', 'cup', 'pup', 'sun',
              'fun', 'bug', 'hug', 'jug', 'rug', 'tug', 'mug'] },

  { id: 4, name: 'Four-Letter Words',   emoji: '📝', color: '#fd9644', group: 'Beginner',
    prompts: ['jump', 'help', 'frog', 'desk', 'kite', 'fish',
              'bird', 'milk', 'cold', 'bold', 'gold', 'fold',
              'kind', 'mind', 'find', 'bind', 'back', 'jack',
              'pack', 'rack', 'rock', 'lock', 'sock', 'dock',
              'pick', 'kick', 'tick', 'deck', 'neck', 'peck'] },

  { id: 5, name: 'Five-Letter Words',   emoji: '🎉', color: '#26de81', group: 'Beginner',
    prompts: ['apple', 'happy', 'smile', 'plant', 'cloud',
              'brain', 'chair', 'drink', 'early', 'frost',
              'grasp', 'house', 'juice', 'light', 'money',
              'night', 'ocean', 'piano', 'queen', 'river',
              'stone', 'tiger', 'voice', 'watch', 'youth',
              'zebra', 'music', 'dream', 'earth', 'candy'] },

  { id: 6, name: 'Simple Phrases',      emoji: '💬', color: '#26de81', group: 'Beginner',
    prompts: ['the cat', 'a big dog', 'my hat', 'run fast',
              'sit down', 'look up', 'come in', 'go out',
              'fly high', 'fall down', 'stand up', 'hold on',
              'move it', 'slow down', 'be kind', 'stay calm',
              'think big', 'work hard', 'play fair', 'be brave'] },

  { id: 7, name: 'Easy Sentences',      emoji: '📖', color: '#26de81', group: 'Beginner',
    prompts: ['The cat sat.', 'A dog ran.', 'I can hop.',
              'She is big.', 'He ran fast.', 'The sun is hot.',
              'A fish swims.', 'I like cats.', 'Dogs are fun.',
              'We can run.', 'She can jump.', 'He likes milk.',
              'The bird flew.', 'I see a frog.', 'We eat cake.',
              'The sky is blue.', 'I love books.', 'You are smart.'] },

  // ── Elementary (ages 10-12) ──────────────────────────────
  { id: 8, name: 'Common Words',        emoji: '📚', color: '#45aaf2', group: 'Elementary',
    prompts: ['school', 'friend', 'water', 'light', 'world',
              'music', 'story', 'paper', 'table', 'mother',
              'father', 'brother', 'sister', 'family', 'flower',
              'garden', 'window', 'answer', 'people', 'travel',
              'always', 'before', 'during', 'follow', 'happen',
              'kitchen', 'library', 'million', 'nothing', 'outside'] },

  { id: 9, name: 'Word Pairs',          emoji: '🔗', color: '#45aaf2', group: 'Elementary',
    prompts: ['black and white', 'up and down', 'left and right',
              'hot and cold', 'fast and slow', 'day and night',
              'big and small', 'old and new', 'near and far',
              'open and close', 'push and pull', 'start and stop',
              'come and go', 'rise and fall', 'give and take',
              'cats and dogs', 'sun and moon', 'land and sea',
              'bread and butter', 'salt and pepper'] },

  { id: 10, name: 'Simple Sentences',   emoji: '✏️', color: '#45aaf2', group: 'Elementary',
    prompts: ['The sun shines every day.',
              'Birds fly in the blue sky.',
              'I love to read good books.',
              'We play outside after school.',
              'My dog likes to chase the ball.',
              'The flowers bloom in the spring.',
              'She drinks water every morning.',
              'He runs to school every day.',
              'We eat lunch at noon together.',
              'They sing songs and dance.',
              'I enjoy drawing and painting.',
              'She writes letters to her friends.',
              'He learned to swim last summer.',
              'The rain falls gently on the roof.',
              'We recycle paper, glass, and cans.'] },

  { id: 11, name: 'Longer Sentences',   emoji: '✏️', color: '#45aaf2', group: 'Elementary',
    prompts: ['The quick brown fox jumps over the lazy dog.',
              'She went to the store to buy fresh apples.',
              'My favorite subject in school is mathematics.',
              'The children played in the park all afternoon.',
              'He learned to ride his bike last summer.',
              'We watched a funny movie with our family.',
              'The teacher gave us a very interesting assignment.',
              'I enjoy listening to music while doing homework.',
              'She always remembers to say please and thank you.',
              'The library has thousands of interesting books to read.',
              'We went on a field trip to the science museum.',
              'He practiced playing the piano for two hours.'] },

  { id: 12, name: 'Numbers and Text',   emoji: '🔢', color: '#45aaf2', group: 'Elementary',
    prompts: ['I have 5 cats at home.',
              'She is 10 years old today.',
              'We need 3 cups of sugar.',
              'There are 24 hours in a day.',
              'The class has 30 students.',
              'Add 15 and 27 to get 42.',
              'The book has 100 pages.',
              'We walked 2 miles to the park.',
              'I scored 95 on my math test.',
              'She bought 4 pencils and 2 pens.',
              'The recipe calls for 2 eggs.',
              'He is 1st in his class of 25.',
              'We need 8 players for a team.',
              'The store opens at 9 a.m.',
              'She has been studying for 3 hours.'] },

  // ── Middle (ages 13-15) ──────────────────────────────────
  { id: 13, name: 'Informative Text',   emoji: '📰', color: '#a55eea', group: 'Middle',
    prompts: ['The library is a wonderful place to discover new ideas.',
              'Many animals live in the rainforest ecosystem.',
              'Exercise helps keep your body strong and your mind sharp.',
              'Reading every day can greatly improve your vocabulary.',
              'Technology has changed the way we communicate with others.',
              'The ocean covers most of the surface of the Earth.',
              'Plants need sunlight, water, and nutrients from soil to grow.',
              'Learning a new language takes patience, time, and practice.',
              'Music can express emotions that are difficult to put into words.',
              'Teamwork is important in both sports and academic settings.',
              'Scientists study the natural world to understand how it works.',
              'History teaches us valuable lessons about the past.',
              'Mathematics is the language of science and engineering.',
              'Healthy habits formed in youth tend to last a lifetime.',
              'Art allows people to express their creativity and emotions.'] },

  { id: 14, name: 'Punctuation',        emoji: '❓', color: '#a55eea', group: 'Middle',
    prompts: ['What time does the movie start?',
              'Wait, I need to think about this!',
              'She asked, "Are you coming with us?"',
              'First, add the numbers; then, subtract the result.',
              'He said: "I will arrive at 3:00 p.m."',
              'We need: apples, bananas, and fresh oranges.',
              'Look out! There is ice on the road ahead.',
              'He runs every morning, even in the rain.',
              'The report is due Friday; please do not be late.',
              'Can you believe it? We won the championship!',
              'She has three hobbies: reading, painting, and hiking.',
              'Yes! That is exactly the right answer!',
              'The meeting starts at 9:00 a.m. sharp.',
              'Please bring: a pencil, paper, and a ruler.',
              'It is a great day, is it not?'] },

  { id: 15, name: 'Facts and Knowledge', emoji: '🌐', color: '#a55eea', group: 'Middle',
    prompts: ['The Earth orbits the Sun once every 365 days.',
              'Water freezes at 32 degrees Fahrenheit or 0 Celsius.',
              'Abraham Lincoln was the 16th President of the United States.',
              'The speed of light is approximately 186,000 miles per second.',
              'The Great Wall of China stretches over 13,000 miles.',
              'Shakespeare wrote 37 plays and 154 sonnets in his lifetime.',
              'Mount Everest is the tallest mountain at 29,032 feet.',
              'The human body has 206 bones and over 600 muscles.',
              'Photosynthesis converts sunlight and water into food for plants.',
              'The Pacific Ocean is the largest ocean on Earth.',
              'Gravity is the force that keeps planets in orbit around stars.',
              'The human brain contains approximately 86 billion neurons.',
              'The speed of sound is about 767 miles per hour at sea level.',
              'The Amazon River flows through nine countries in South America.',
              'DNA carries the genetic information for all living organisms.'] },

  // ── High School (ages 16-18) ─────────────────────────────
  { id: 16, name: 'Advanced Writing',   emoji: '🎓', color: '#fc5c65', group: 'High School',
    prompts: ['The theory of relativity fundamentally changed our understanding of space and time.',
              'Democracy requires an informed and engaged citizenry to function effectively.',
              'The Industrial Revolution brought profound economic and social transformations.',
              'Critical thinking is an essential skill for navigating our complex modern world.',
              'Literature allows us to explore the full spectrum of human experience and emotion.',
              'The scientific method involves careful observation, hypothesis, and experimentation.',
              'Effective communication forms the foundation of all successful human relationships.',
              'Environmental conservation is vital for ensuring a sustainable future for all life.',
              'Economic systems shape the distribution of resources and opportunities in society.',
              'Philosophy poses fundamental questions about existence, knowledge, and morality.',
              'The arts play a crucial role in preserving cultural heritage and identity.',
              'Technological innovation continues to reshape the boundaries of human possibility.',
              'Global collaboration is essential for addressing the challenges of the 21st century.',
              'Education empowers individuals to participate fully in civic and economic life.',
              'Diversity of thought and background strengthens communities and drives innovation.'] },

  { id: 17, name: 'Speed Challenge I',  emoji: '⚡', color: '#fc5c65', group: 'High School',
    prompts: ['The five boxing wizards jump quickly over the lazy dogs.',
              'Pack my box with five dozen liquor jugs and ship them fast.',
              'How vexingly quick daft zebras jump over the brown fence.',
              'Sphinx of black quartz, judge my vow and find it worthy.',
              'Two driven jocks help fax my big quiz to the waiting editor.',
              'Quick zephyrs blow, vexing daft Jim while he reads the news.',
              'The quick onyx goblin jumps over the lazy dwarf by the fire.',
              'Crazy Fredrick bought many very exquisite opal jewels last year.',
              'We promptly judged antique ivory buckles for the prize.',
              'A wizard quickly jinxed the gnomes before they leaped.',
              'Jinxed wizards pluck ivy from the big quartz valley on the slope.',
              'Five quacking zephyrs jolt my wax bed before the big storm hits.',
              'Just keep examining every low bid quoted for zinc etchings.',
              'The job requires extra pluck and zeal from every young worker.',
              'Waxy and quivering, the jokester plunged his fez into the drum.'] },

  { id: 18, name: 'Speed Challenge II', emoji: '🚀', color: '#fc5c65', group: 'High School',
    prompts: ['Artificial intelligence is reshaping industries and transforming the global economy.',
              'The neuroscience of learning reveals how memory consolidation occurs during sleep.',
              'Quantum computing promises to solve problems beyond the reach of classical computers.',
              'The geopolitical landscape of the 21st century is defined by technological competition.',
              'Analyzing primary sources is fundamental to rigorous historical inquiry.',
              'The biochemical processes underlying cellular respiration are remarkably complex.',
              'Philosophical ethics examines the principles that guide our moral decision-making.',
              'The elegance of calculus underpins modern physics and engineering disciplines.',
              'Climate change represents one of the defining challenges of the current century.',
              'The interplay between genetics and environment shapes every aspect of human development.',
              'Economic globalization has created interdependencies that affect every nation on Earth.',
              'The study of linguistics reveals the deep structure and diversity of human language.',
              'Advancements in medicine have dramatically increased average life expectancy worldwide.',
              'The philosophy of science questions how we acquire and validate knowledge of the world.',
              'Social media has fundamentally altered how information spreads through modern society.'] },

  { id: 19, name: 'Master Typist',      emoji: '🏆', color: '#fc5c65', group: 'High School',
    prompts: ['To be, or not to be, that is the question.',
              'It was the best of times, it was the worst of times, it was the age of wisdom.',
              'We hold these truths to be self-evident, that all men are created equal.',
              'Ask not what your country can do for you; ask what you can do for your country.',
              'Four score and seven years ago our fathers brought forth on this continent a new nation.',
              'The greatest glory in living lies not in never falling, but in rising every time we fall.',
              'Life is what happens to you while you are busy making other plans for the future.',
              'In three words I can sum up everything I have learned about life: it goes on.',
              'Success is not final; failure is not fatal: it is the courage to continue that counts.',
              'The future belongs to those who believe in the beauty of their dreams and act on them.',
              'You miss one hundred percent of the shots you do not take.',
              'In the middle of every difficulty lies opportunity.',
              'It does not matter how slowly you go as long as you do not stop.',
              'Believe you can and you are halfway there.',
              'The only way to do great work is to love what you do and never stop learning.'] },
];
